export const MENU_ITEMS = 'MENU_ITEMS'
export const SET_PAGE_VIEW = 'SET_PAGE_VIEW'
export const SET_DETAIL_VIEW_CONTEXT = 'SET_DETAIL_VIEW_CONTEXT'
export const SET_SIDEBAR_CONTENTS = 'SET_SIDEBAR_CONTENTS'
